version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  sponsors-receiver:
    lang: node12
    handler: ./sponsors-receiver
    image: sponsors-receiver:latest
    environment:
      write_debug: true

